println("Test")
println("Line2")
println("hallo")
println("Scala stinkt")
println("Baum")
println("Hallo Welt")
println("opa")
println("oma")
println("Tante")
println("Onkel")
println("Hallo")
println("Tschüss")