# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ main, struktur, feature1 ]
  pull_request:
    branches: [ main, struktur, feature1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: compile
      run: sbt compile
    - name: run tests
      run: sbt test
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup sbt
      uses: sbt/setup-sbt@v1
    - name: setup JVM
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: run sbt coverage test
      run: sbt clean coverage test
    - name: aggregate reports
      run: sbt coverageAggregate
    - name: test report
      run: sbt coverageReport
    - name: Submit to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN }}
      run: sbt coveralls

      
  


    
    
